language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
branches:
  only:
    - master
# matrix:
#   allow_failures:
#     - rvm: jruby-19mode
#     - rvm: rbx-19mode
